// <auto-generated />
using System;
using BC_CampusLearn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BC_CampusLearn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720094908_DatabaseRedesign")]
    partial class DatabaseRedesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTimeOffset>("DateBooked")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StudentObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("StudentTenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TutorAvailabilityId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("TutorAvailabilityId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingDocument", b =>
                {
                    b.Property<int>("BookingDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDocumentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BookingDocumentId");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.ToTable("BookingDocuments", t =>
                        {
                            t.HasCheckConstraint("CK_BookingDocuments_Position", "[Position] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingPreparationLink", b =>
                {
                    b.Property<int>("BookingPreparationLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingPreparationLinkId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("BookingPreparationLinkId");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.ToTable("BookingPreparationLinks", t =>
                        {
                            t.HasCheckConstraint("CK_BookingPreparationLinks_Position", "[Position] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.CourseModule", b =>
                {
                    b.Property<int>("CourseModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseModuleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CourseModuleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("EntraTenantId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TutorId");

                    b.HasIndex("EntraTenantId", "EntraObjectId")
                        .IsUnique()
                        .HasFilter("[EntraTenantId] IS NOT NULL AND [EntraObjectId] IS NOT NULL");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.Property<int>("TutorAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorAvailabilityId"));

                    b.Property<DateTimeOffset>("AvailableTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CourseModuleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorAvailabilityId");

                    b.HasIndex("CourseModuleId");

                    b.HasIndex("TutorId", "CourseModuleId", "AvailableTime")
                        .IsUnique();

                    b.ToTable("TutorAvailabilities");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("CourseModuleId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "CourseModuleId");

                    b.HasIndex("CourseModuleId");

                    b.ToTable("TutorCourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.TutorAvailability", "TutorAvailability")
                        .WithOne("Booking")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.Booking", "TutorAvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TutorAvailability");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingDocument", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("Documents")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingPreparationLink", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("PreparationLinks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.CourseModule", "CourseModule")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.CourseModule", "CourseModule")
                        .WithMany("TutorCourseModules")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorCourseModules")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("PreparationLinks");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.CourseModule", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("TutorCourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("TutorCourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
