// <auto-generated />
using System;
using BC_CampusLearn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BC_CampusLearn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721135707_UpdatedProgrammesModules")]
    partial class UpdatedProgrammesModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTimeOffset>("DateBooked")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StudentObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("StudentTenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TutorAvailabilityId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("TutorAvailabilityId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingDocument", b =>
                {
                    b.Property<int>("BookingDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDocumentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BookingDocumentId");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.ToTable("BookingDocuments", t =>
                        {
                            t.HasCheckConstraint("CK_BookingDocuments_Position", "[Position] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingPreparationLink", b =>
                {
                    b.Property<int>("BookingPreparationLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingPreparationLinkId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("BookingPreparationLinkId");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.ToTable("BookingPreparationLinks", t =>
                        {
                            t.HasCheckConstraint("CK_BookingPreparationLinks_Position", "[Position] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.CourseModule", b =>
                {
                    b.Property<int>("CourseModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseModuleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CourseModuleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeModule", b =>
                {
                    b.Property<int>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<string>("ModuleCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("ProgrammeId", "ModuleCode");

                    b.ToTable("ProgrammeModule", (string)null);

                    b.HasData(
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "ACW181",
                            ModuleName = "Academic Writing 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "COA181",
                            ModuleName = "Computer Architecture 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "DBD181",
                            ModuleName = "Database Development 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "INF181",
                            ModuleName = "Information Systems 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "INL101",
                            ModuleName = "Innovation and Leadership 101",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "INL102",
                            ModuleName = "Innovation and Leadership 102",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "LPR181",
                            ModuleName = "Linear Programming 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "MAT181",
                            ModuleName = "Mathematics 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "NWD181",
                            ModuleName = "Networking Development 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "PRG181",
                            ModuleName = "Programming 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "PRG182",
                            ModuleName = "Programming 182",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "STA181",
                            ModuleName = "Statistics 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "WPR181",
                            ModuleName = "Web Programming 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "BUM181",
                            ModuleName = "Business Management 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "ENT181",
                            ModuleName = "Entrepreneurship 181",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "DBD281",
                            ModuleName = "Database Development 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "INF281",
                            ModuleName = "Information Systems 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "INL201",
                            ModuleName = "Innovation and Leadership 201",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "INL202",
                            ModuleName = "Innovation and Leadership 202",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "LPR281",
                            ModuleName = "Linear Programming 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "MAT281",
                            ModuleName = "Mathematics 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "PRG281",
                            ModuleName = "Programming 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "PRG282",
                            ModuleName = "Programming 282",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "PMM281",
                            ModuleName = "Project Management 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "STA281",
                            ModuleName = "Statistics 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "WPR281",
                            ModuleName = "Web Programming 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "SAD281",
                            ModuleName = "Software Analysis & Design 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "DWH281",
                            ModuleName = "Data Warehousing 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "IOT281",
                            ModuleName = "Internet Of Things 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "SWT281",
                            ModuleName = "Software Testing 281",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "RSH381",
                            ModuleName = "Research Methods 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "DBD381",
                            ModuleName = "Database Development 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "INL321",
                            ModuleName = "Innovation and Leadership 321",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "LPR381",
                            ModuleName = "Linear Programming 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "MLG381",
                            ModuleName = "Machine Learning 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "PRJ381",
                            ModuleName = "Project 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "PMM381",
                            ModuleName = "Project Management 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "PRG381",
                            ModuleName = "Programming 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "SEN381",
                            ModuleName = "Software Engineering 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "WPR381",
                            ModuleName = "Web Programming 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "BIN381",
                            ModuleName = "Data Science 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "DBA381",
                            ModuleName = "Database Administration 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "STA381",
                            ModuleName = "Statistics 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "INM381",
                            ModuleName = "Innovation Management 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "MLG382",
                            ModuleName = "Machine Learning 382",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "UAX381",
                            ModuleName = "User Experience Design 381",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "AIT481",
                            ModuleName = "Applied Information Technology 481",
                            YearOfStudy = 4
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "AIT482",
                            ModuleName = "Applied Information Technology 482",
                            YearOfStudy = 4
                        },
                        new
                        {
                            ProgrammeId = 1,
                            ModuleCode = "DST481",
                            ModuleName = "Dissertation 481",
                            YearOfStudy = 4
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "ACW171",
                            ModuleName = "Academic Writing 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "COA171",
                            ModuleName = "Computer Architecture 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "DBD171",
                            ModuleName = "Database Development 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "ENG171",
                            ModuleName = "English Communication 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "INF171",
                            ModuleName = "Information Systems 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "INL101",
                            ModuleName = "Innovation and Leadership 101",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "INL102",
                            ModuleName = "Innovation and Leadership 102",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "MAT171",
                            ModuleName = "Mathematics 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "NWD171",
                            ModuleName = "Networking Development 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "PRG171",
                            ModuleName = "Programming 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "PRG172",
                            ModuleName = "Programming 172",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "STA171",
                            ModuleName = "Statistics 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "WPR171",
                            ModuleName = "Web Programming 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "BUM171",
                            ModuleName = "Business Management 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "ENT171",
                            ModuleName = "Entrepreneurship 171",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "CNA271",
                            ModuleName = "Cloud-Native Application Architecture 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "DBD221",
                            ModuleName = "Database Development 221",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "ERP271",
                            ModuleName = "Enterprise Systems 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "ETH271",
                            ModuleName = "Ethics 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "INF271",
                            ModuleName = "Information Systems 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "INL201",
                            ModuleName = "Innovation and Leadership 201",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "INL202",
                            ModuleName = "Innovation and Leadership 202",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "LPR171",
                            ModuleName = "Linear Programming 171",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "PRG271",
                            ModuleName = "Programming 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "PRG272",
                            ModuleName = "Programming 272",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "PMM271",
                            ModuleName = "Project Management 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "STA271",
                            ModuleName = "Statistics 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "WPR271",
                            ModuleName = "Web Programming 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "IOT271",
                            ModuleName = "Internet Of Things 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "SWT271",
                            ModuleName = "Software Testing 271",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "BIN371",
                            ModuleName = "Business Intelligence 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "CNA371",
                            ModuleName = "Cloud-Native Application Programming 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "DAL371",
                            ModuleName = "Data Analytics 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "DBD371",
                            ModuleName = "Database Development 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "INL371",
                            ModuleName = "Innovation and Leadership 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "PRG371",
                            ModuleName = "Programming 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "PRJ371",
                            ModuleName = "Project 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "PMM371",
                            ModuleName = "Project Management 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "SAD371",
                            ModuleName = "Software Analysis & Design 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "SEN371",
                            ModuleName = "Software Engineering 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "WPR371",
                            ModuleName = "Web Programming 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "INM371",
                            ModuleName = "Innovation Management 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 2,
                            ModuleCode = "UAX371",
                            ModuleName = "User Experience Design 371",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "BUC161",
                            ModuleName = "Business Communication 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "BME161",
                            ModuleName = "Business Management and Entrepreneurship 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "COA161",
                            ModuleName = "Computer Architecture 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "DBC161",
                            ModuleName = "Database Concept 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "DBF161",
                            ModuleName = "Database Functionality 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "EUC161",
                            ModuleName = "End User Computing 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "INL161",
                            ModuleName = "Innovation and Leadership 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "IOT161",
                            ModuleName = "Internet of Things 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "MAT161",
                            ModuleName = "Mathematics 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "NWD161",
                            ModuleName = "Network Development 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "PRG161",
                            ModuleName = "Programming 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "PRL161",
                            ModuleName = "Programming Preliminaries 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "WPR161",
                            ModuleName = "Web Programming 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "STA161",
                            ModuleName = "Statistics 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "DBD261",
                            ModuleName = "Database Development 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "ERP261",
                            ModuleName = "Enterprise Systems 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "INL261",
                            ModuleName = "Innovation and Leadership 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "ILE261",
                            ModuleName = "IT Law and Ethics 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "PMM261",
                            ModuleName = "Project Management 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "DBD262",
                            ModuleName = "Database Development 262",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "DBR261",
                            ModuleName = "Database Reporting 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "DBA261",
                            ModuleName = "Database Administration 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "CNA261",
                            ModuleName = "Cloud-Native Application Architecture 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "IOT261",
                            ModuleName = "Internet of Things 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "OPS261",
                            ModuleName = "Operating Systems 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "OPS262",
                            ModuleName = "Operating Systems 262",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "OPS263",
                            ModuleName = "Operating Systems 263",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "SEC261",
                            ModuleName = "Security 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "PRG261",
                            ModuleName = "Programming 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "PRG262",
                            ModuleName = "Programming 262",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "SWA261",
                            ModuleName = "Software Analysis and Design 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "SWT261",
                            ModuleName = "Software Testing 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "SWT262",
                            ModuleName = "Software Testing 262 (Elective)",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "UXD261",
                            ModuleName = "User Experience Design 261 (Elective)",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 3,
                            ModuleCode = "WPR261",
                            ModuleName = "Web Programming 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-INL161",
                            ModuleName = "Innovation and Leadership 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-EUC161",
                            ModuleName = "End-User Computing 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-BUC161",
                            ModuleName = "Business Communication 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-BME161",
                            ModuleName = "Business Management & Entrepreneurship 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-PRL161",
                            ModuleName = "Programming Preliminaries 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-PRG161",
                            ModuleName = "Programming 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-WPR161",
                            ModuleName = "Web Programming 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-DBC161",
                            ModuleName = "Database Concepts 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-DBF161",
                            ModuleName = "Database Functionality 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "MAT161",
                            ModuleName = "Applied Mathematics 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-STA161",
                            ModuleName = "Statistics 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-COA161",
                            ModuleName = "Computer Architecture 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-NWD161",
                            ModuleName = "Network Development 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-IOT161",
                            ModuleName = "Internet of Things 161",
                            YearOfStudy = 1
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-INL261",
                            ModuleName = "Innovation and Leadership 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-ERP261",
                            ModuleName = "Enterprise Systems 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-ILE261",
                            ModuleName = "IT Law & Ethics 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-PMM261",
                            ModuleName = "Project Management 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-DBD261",
                            ModuleName = "Database Development 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-PRG261",
                            ModuleName = "Programming 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-PRG262",
                            ModuleName = "Programming 262",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-SWT261",
                            ModuleName = "Software Testing 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-SWA261",
                            ModuleName = "Software Analysis & Design 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-WPR261",
                            ModuleName = "Web Programming 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-SWT262",
                            ModuleName = "Software Testing 262",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-UXD261",
                            ModuleName = "User Experience & Design 261",
                            YearOfStudy = 2
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-DBD262",
                            ModuleName = "Database Development 262",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-DBR261",
                            ModuleName = "Database Reporting 261",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-DBA261",
                            ModuleName = "Database Administration 261",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-WFS361",
                            ModuleName = "Web Front-End Scripting 361",
                            YearOfStudy = 3
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-PRJ361",
                            ModuleName = "Project 361",
                            YearOfStudy = 4
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-INL361",
                            ModuleName = "Innovation & Leadership 361",
                            YearOfStudy = 4
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-AIT361",
                            ModuleName = "Applied Information Technology 361",
                            YearOfStudy = 4
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-WSP361",
                            ModuleName = "Work-Simulation Project 361",
                            YearOfStudy = 4
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-WSE361",
                            ModuleName = "Web Servers 361",
                            YearOfStudy = 4
                        },
                        new
                        {
                            ProgrammeId = 4,
                            ModuleCode = "D-WDB361",
                            ModuleName = "Web Database 361",
                            YearOfStudy = 4
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProgrammeOfStudy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bachelor of Computing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bachelor of Information Technology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diploma in Information Technology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diploma for Deaf Students"
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("EntraTenantId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TutorId");

                    b.HasIndex("EntraTenantId", "EntraObjectId")
                        .IsUnique()
                        .HasFilter("[EntraTenantId] IS NOT NULL AND [EntraObjectId] IS NOT NULL");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.Property<int>("TutorAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorAvailabilityId"));

                    b.Property<DateTimeOffset>("AvailableTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CourseModuleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorAvailabilityId");

                    b.HasIndex("CourseModuleId");

                    b.HasIndex("TutorId", "CourseModuleId", "AvailableTime")
                        .IsUnique();

                    b.ToTable("TutorAvailabilities");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("CourseModuleId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "CourseModuleId");

                    b.HasIndex("CourseModuleId");

                    b.ToTable("TutorCourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.TutorAvailability", "TutorAvailability")
                        .WithOne("Booking")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.Booking", "TutorAvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TutorAvailability");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingDocument", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("Documents")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingPreparationLink", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("PreparationLinks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeModule", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", "Programme")
                        .WithMany("Modules")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.CourseModule", "CourseModule")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.CourseModule", "CourseModule")
                        .WithMany("TutorCourseModules")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorCourseModules")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("PreparationLinks");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.CourseModule", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("TutorCourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("TutorCourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
