// <auto-generated />
using System;
using BC_CampusLearn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BC_CampusLearn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005140955_AddTutorHeadReviewDeadlineMonthEndOption")]
    partial class AddTutorHeadReviewDeadlineMonthEndOption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("BcUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AdminId");

                    b.HasIndex("BcUserId")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.AdminSessionReview", b =>
                {
                    b.Property<int>("AdminSessionReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminSessionReviewId"));

                    b.Property<bool>("AllReviewsSubmitted")
                        .HasColumnType("bit");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<bool>("ConcernsResolvedOrDocumented")
                        .HasColumnType("bit");

                    b.Property<bool>("EvidenceSupportsApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadConfirmedQuality")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadConfirmedSession")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReviewerBcUserId")
                        .HasColumnType("int");

                    b.HasKey("AdminSessionReviewId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ReviewerBcUserId");

                    b.ToTable("AdminSessionReview", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BcUser", b =>
                {
                    b.Property<int>("BcUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BcUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EncryptedEntraObjectId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EncryptedEntraTenantId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EncryptedGeminiApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("EntraIdentityLookupHash")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<bool>("IsAdministrativeAccessActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublicActivityEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonnelNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PublicActivityDisabledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicActivityDisabledReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("SessionReviewsLastViewedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BcUserId");

                    b.HasIndex("EntraIdentityLookupHash")
                        .IsUnique()
                        .HasFilter("[EntraIdentityLookupHash] IS NOT NULL");

                    b.HasIndex("PersonnelNumber")
                        .IsUnique()
                        .HasFilter("[PersonnelNumber] IS NOT NULL");

                    b.ToTable("BcUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_BcUsers_Role", "[Role] BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateBooked")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ReminderSentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ScheduledStartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StudentBcUserId")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StudyAreaId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("TutorHeadReviewAvailableAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("ProgrammeModuleId");

                    b.HasIndex("StudentBcUserId");

                    b.HasIndex("StudyAreaId");

                    b.HasIndex("TutorHeadReviewAvailableAt");

                    b.HasIndex("TutorId", "ProgrammeModuleId");

                    b.HasIndex("TutorId", "ScheduledStartTime");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Duration_OneHour", "[Duration] = 1");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingDocument", b =>
                {
                    b.Property<int>("BookingDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDocumentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BookingDocumentId");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.ToTable("BookingDocuments", t =>
                        {
                            t.HasCheckConstraint("CK_BookingDocuments_Position", "[Position] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingPreparationLink", b =>
                {
                    b.Property<int>("BookingPreparationLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingPreparationLinkId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("BookingPreparationLinkId");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.ToTable("BookingPreparationLinks", t =>
                        {
                            t.HasCheckConstraint("CK_BookingPreparationLinks_Position", "[Position] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingStatusHistory", b =>
                {
                    b.Property<int>("BookingStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingStatusHistoryId"));

                    b.Property<bool>("AvailabilityReopened")
                        .HasColumnType("bit");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ChangedByBcUserId")
                        .HasColumnType("int");

                    b.Property<bool>("ChangedBySystem")
                        .HasColumnType("bit");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("BookingStatusHistoryId");

                    b.HasIndex("ChangedByBcUserId");

                    b.HasIndex("BookingId", "ChangedAt");

                    b.ToTable("BookingStatusHistory", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.CampusEvent", b =>
                {
                    b.Property<int>("CampusEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusEventId"));

                    b.Property<string>("BannerImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Disclaimer")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("PublishAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CampusEventId");

                    b.HasIndex("IsPublished", "PublishAt", "EndsAt");

                    b.ToTable("CampusEvent", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.CampusEventDetail", b =>
                {
                    b.Property<int>("CampusEventDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusEventDetailId"));

                    b.Property<int>("CampusEventId")
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("CampusEventDetailId");

                    b.HasIndex("CampusEventId", "Position");

                    b.ToTable("CampusEventDetail", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResource", b =>
                {
                    b.Property<int>("LearningResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningResourceId"));

                    b.Property<bool>("AllowSubscriberComments")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset?>("DatePublished")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Link1")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Link2")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TutorLastViewedDiscussionAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LearningResourceId");

                    b.HasIndex("ProgrammeModuleId");

                    b.HasIndex("TutorId", "Status", "DateCreated");

                    b.ToTable("LearningResource", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResourceDocument", b =>
                {
                    b.Property<int>("ResourceDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceDocumentId"));

                    b.Property<DateTimeOffset>("DateUploaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("ResourceDocumentId");

                    b.HasIndex("ResourceId");

                    b.ToTable("LearningResourceDocuments", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.MeetingLink", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("BookingId");

                    b.ToTable("MeetingLink", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.PlatformSettings", b =>
                {
                    b.Property<int>("PlatformSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformSettingsId"));

                    b.Property<string>("AcademicSemester")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("Announcement")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BookingTermsAndConditions")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampusTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("DateTimeFormat")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsAnnouncementEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMaintenanceModeEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTutorHeadReviewDeadlineRecurring")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateOnly>("TutorHeadReviewDeadline")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TutorHeadReviewPeriodEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TutorHeadReviewPeriodStartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedByBcUserId")
                        .HasColumnType("int");

                    b.Property<bool>("UseLastDayOfMonthForTutorHeadReviewDeadline")
                        .HasColumnType("bit");

                    b.HasKey("PlatformSettingsId");

                    b.HasIndex("UpdatedByBcUserId");

                    b.ToTable("PlatformSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlatformSettings_AcademicYear", "[AcademicYear] BETWEEN 2000 AND 2200");

                            t.HasCheckConstraint("CK_PlatformSettings_Singleton", "[PlatformSettingsId] = 1");

                            t.HasCheckConstraint("CK_PlatformSettings_TutorHeadReviewPeriod", "[TutorHeadReviewPeriodEndDate] >= [TutorHeadReviewPeriodStartDate] AND [TutorHeadReviewDeadline] >= [TutorHeadReviewPeriodEndDate]");
                        });

                    b.HasData(
                        new
                        {
                            PlatformSettingsId = 1,
                            AcademicSemester = "Semester 1",
                            AcademicYear = 2026,
                            BookingTermsAndConditions = "All appointments with tutors must be scheduled a day ahead.\nAll sessions are limited to 1 hour.\nYou must come prepared for the sessions.\nYou will be given exercises to complete during your sessions.\nAll online sessions via MS Teams are recorded.\nAll face-to-face sessions are held in the study room.\nRespect the time and effort of your tutor.\nYou will be required to complete a tutor evaluation form.",
                            CampusTimeZoneId = "Africa/Johannesburg",
                            CurrencyCode = "ZAR",
                            DateTimeFormat = "dd MMMM yyyy, HH:mm",
                            IsAnnouncementEnabled = false,
                            IsMaintenanceModeEnabled = false,
                            IsTutorHeadReviewDeadlineRecurring = true,
                            RowVersion = new byte[0],
                            SupportEmail = "tutors@belgiumcampus.ac.za",
                            TutorHeadReviewDeadline = new DateOnly(2026, 10, 5),
                            TutorHeadReviewPeriodEndDate = new DateOnly(2026, 9, 30),
                            TutorHeadReviewPeriodStartDate = new DateOnly(2026, 9, 1),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UseLastDayOfMonthForTutorHeadReviewDeadline = false
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeModule", b =>
                {
                    b.Property<int>("ProgrammeModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgrammeModuleId"));

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("ProgrammeModuleId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("ProgrammeModule", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProgrammeOfStudy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bachelor of Computing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bachelor of Information Technology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diploma in Information Technology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diploma for Deaf Students"
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("ResourceId", "IsPinned", "DateCreated");

                    b.ToTable("ResourceComments", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceSubscription", b =>
                {
                    b.Property<int>("ResourceSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceSubscriptionId"));

                    b.Property<DateTimeOffset>("DateSubscribed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResourceSubscriptionId");

                    b.HasIndex("PersonnelNumber", "ModuleCode")
                        .IsUnique();

                    b.ToTable("ResourceSubscriptions", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceTutorNomination", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DenominatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DenominatedByBcUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("NominatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NominatedByBcUserId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "ProgrammeModuleId");

                    b.HasIndex("DenominatedByBcUserId");

                    b.HasIndex("NominatedByBcUserId");

                    b.HasIndex("ProgrammeModuleId");

                    b.ToTable("ResourceTutorNominations");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionAiAssessment", b =>
                {
                    b.Property<int>("SessionAiAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionAiAssessmentId"));

                    b.Property<string>("AssessmentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GeneratedByBcUserId")
                        .HasColumnType("int");

                    b.HasKey("SessionAiAssessmentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("GeneratedByBcUserId");

                    b.ToTable("SessionAiAssessments", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionExecution", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpectedCompletionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StartSource")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BookingId");

                    b.HasIndex("ExpectedCompletionAt");

                    b.ToTable("SessionExecutions", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionMessage", b =>
                {
                    b.Property<long>("SessionMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionMessageId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("RecipientBcUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderBcUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SessionMessageId");

                    b.HasIndex("SenderBcUserId");

                    b.HasIndex("BookingId", "SentAt");

                    b.HasIndex("RecipientBcUserId", "ReadAt", "SentAt");

                    b.ToTable("SessionMessages", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionReview", b =>
                {
                    b.Property<int>("SessionReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionReviewId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ConcernLevel")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Decision")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EvidenceConsistency")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ExplanationClarity")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("ModuleAndTopicCoverage")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("OverallAssessment")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int?>("RevieweeBcUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerBcUserId")
                        .HasColumnType("int");

                    b.Property<string>("SessionStructure")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("StudentEngagement")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("SessionReviewId");

                    b.HasIndex("RevieweeBcUserId");

                    b.HasIndex("ReviewerBcUserId");

                    b.HasIndex("BookingId", "ReviewerBcUserId")
                        .IsUnique();

                    b.ToTable("SessionReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionReviews_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SettingAuditLog", b =>
                {
                    b.Property<long>("SettingAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SettingAuditLogId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ChangedByBcUserId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("SettingAuditLogId");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByBcUserId");

                    b.ToTable("SettingAuditLogs", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.StudentEvaluation", b =>
                {
                    b.Property<int>("StudentEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentEvaluationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ImproveBCProgramme")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte>("ModeRating")
                        .HasColumnType("tinyint");

                    b.Property<string>("PlatformExperience")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("PlatformRating")
                        .HasColumnType("tinyint");

                    b.Property<string>("TutorAdvice")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TutorExplanation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TutorFriendliness")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TutorHelp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TutorInterest")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TutorParticipation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TutorPunctuality")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TutorResponse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TutorTopic")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TutoringMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TutoringService")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StudentEvaluationId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("StudentEvaluations", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudentEvaluations_ModeRating", "[ModeRating] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_StudentEvaluations_PlatformRating", "[PlatformRating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.StudyArea", b =>
                {
                    b.Property<int>("StudyAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudyAreaId"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudyAreaId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StudyAreas");

                    b.HasData(
                        new
                        {
                            StudyAreaId = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Online"
                        },
                        new
                        {
                            StudyAreaId = 2,
                            Description = "Located next to the Chi classroom.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Chi study"
                        },
                        new
                        {
                            StudyAreaId = 3,
                            Description = "Located next to the Pi classroom on Main Campus.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Rou"
                        },
                        new
                        {
                            StudyAreaId = 4,
                            Description = "Located at the Waterloop residence.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Waterloop"
                        },
                        new
                        {
                            StudyAreaId = 5,
                            Description = "Located at the Florenville residence.",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Florenville"
                        },
                        new
                        {
                            StudyAreaId = 6,
                            Description = "Located at the West Campus residence.",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "West Campus"
                        },
                        new
                        {
                            StudyAreaId = 7,
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Brugge"
                        },
                        new
                        {
                            StudyAreaId = 8,
                            Description = "Located next to the Academia building.",
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Main Library & Study area"
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<int>("ApplicationStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("BcUserId")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CampusOfStudy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DemonstrationVideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InterviewDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("InterviewLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InterviewNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InterviewPreparationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("InterviewScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OverallAverage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("PreferredTutoringMode")
                        .HasColumnType("int");

                    b.Property<string>("PreviousTutoringExperience")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForTutoring")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortlistReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("TeachingStyle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("TutorId");

                    b.HasIndex("BcUserId")
                        .IsUnique();

                    b.HasIndex("ProgrammeId");

                    b.ToTable("Tutors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tutors_InterviewDurationMinutes", "[InterviewDurationMinutes] IS NULL OR [InterviewDurationMinutes] BETWEEN 15 AND 240");

                            t.HasCheckConstraint("CK_Tutors_OverallAverage", "[OverallAverage] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Tutors_YearOfStudy", "[YearOfStudy] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorApplicationReviewDecision", b =>
                {
                    b.Property<int>("TutorApplicationReviewDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorApplicationReviewDecisionId"));

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NewStage")
                        .HasColumnType("int");

                    b.Property<int>("PreviousStage")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerBcUserId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorApplicationReviewDecisionId");

                    b.HasIndex("ReviewerBcUserId");

                    b.HasIndex("TutorId", "ReviewedAt");

                    b.ToTable("TutorApplicationReviewDecisions", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorApplicationSettings", b =>
                {
                    b.Property<int>("TutorApplicationSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorApplicationSettingsId"));

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<bool>("ContinueAfterShortlistLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotifyStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("date");

                    b.Property<int?>("ShortlistLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("TutorApplicationSettingsId");

                    b.ToTable("TutorApplicationSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_TutorApplicationSettings_ShortlistLimit", "[ShortlistLimit] IS NULL OR [ShortlistLimit] > 0");

                            t.HasCheckConstraint("CK_TutorApplicationSettings_Singleton", "[TutorApplicationSettingsId] = 1");
                        });

                    b.HasData(
                        new
                        {
                            TutorApplicationSettingsId = 1,
                            ContinueAfterShortlistLimit = false,
                            IsOpen = false,
                            NotifyStudents = false,
                            UpdatedAt = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.Property<int>("TutorAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorAvailabilityId"));

                    b.Property<DateTimeOffset>("AvailableTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReservationExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReservationToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ReservedByBcUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorAvailabilityId");

                    b.HasIndex("ReservationExpiresAt");

                    b.HasIndex("TutorId", "AvailableTime")
                        .IsUnique();

                    b.ToTable("TutorAvailabilities");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("TutorId", "ProgrammeModuleId");

                    b.HasIndex("ProgrammeModuleId");

                    b.ToTable("TutorCourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorDeregistrationRequest", b =>
                {
                    b.Property<int>("TutorDeregistrationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorDeregistrationRequestId"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorDeregistrationRequestId");

                    b.HasIndex("TutorId", "Status");

                    b.ToTable("TutorDeregistrationRequests");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorDocument", b =>
                {
                    b.Property<int>("TutorDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorDocumentId"));

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TutorDocumentId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorDocuments", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorModuleChangeRequest", b =>
                {
                    b.Property<int>("TutorModuleChangeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorModuleChangeRequestId"));

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorModuleChangeRequestId");

                    b.HasIndex("ProgrammeModuleId");

                    b.HasIndex("TutorId", "ProgrammeModuleId", "Status");

                    b.ToTable("TutorModuleChangeRequests");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorStudentEvaluation", b =>
                {
                    b.Property<int>("TutorEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorEvaluationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousHomework")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RecordingLink")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("SessionPlan")
                        .HasColumnType("bit");

                    b.Property<string>("StudentFocus")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StudentInteract")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StudentIssues")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("StudentPreparationInfo")
                        .HasColumnType("bit");

                    b.Property<bool>("StudentPrepared")
                        .HasColumnType("bit");

                    b.Property<bool>("StudentPunctuality")
                        .HasColumnType("bit");

                    b.Property<string>("TranscriptContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TranscriptOriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("TranscriptSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TranscriptStoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TutorComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TutorEvaluationId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("TutorStudentEvaluations", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.UserNotification", b =>
                {
                    b.Property<long>("UserNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserNotificationId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecipientBcUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("UserNotificationId");

                    b.HasIndex("RecipientBcUserId", "ReadAt", "CreatedAt");

                    b.ToTable("UserNotifications", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Admin", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "BcUser")
                        .WithOne("Admin")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.Admin", "BcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BcUser");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.AdminSessionReview", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("AdminSessionReview")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.AdminSessionReview", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("Bookings")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "StudentBcUser")
                        .WithMany()
                        .HasForeignKey("StudentBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BC_CampusLearn.Models.Entities.StudyArea", "StudyArea")
                        .WithMany("Bookings")
                        .HasForeignKey("StudyAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BC_CampusLearn.Models.Entities.TutorCourseModule", "TutorCourseModule")
                        .WithMany("Bookings")
                        .HasForeignKey("TutorId", "ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("StudentBcUser");

                    b.Navigation("StudyArea");

                    b.Navigation("TutorCourseModule");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingDocument", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("Documents")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingPreparationLink", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("PreparationLinks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "ChangedByBcUser")
                        .WithMany()
                        .HasForeignKey("ChangedByBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("ChangedByBcUser");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.CampusEventDetail", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.CampusEvent", "CampusEvent")
                        .WithMany("Details")
                        .HasForeignKey("CampusEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampusEvent");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResource", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("LearningResources")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("LearningResources")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResourceDocument", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.LearningResource", "Resource")
                        .WithMany("Documents")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.MeetingLink", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("MeetingLink")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.MeetingLink", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.PlatformSettings", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByBcUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeModule", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", "Programme")
                        .WithMany("ProgrammeModules")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceComment", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Author")
                        .WithMany("ResourceComments")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ResourceComments_Authors");

                    b.HasOne("BC_CampusLearn.Models.Entities.ResourceComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ResourceComments_Parent");

                    b.HasOne("BC_CampusLearn.Models.Entities.LearningResource", "Resource")
                        .WithMany("Comments")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ResourceComments_Resources");

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceTutorNomination", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", null)
                        .WithMany()
                        .HasForeignKey("DenominatedByBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", null)
                        .WithMany()
                        .HasForeignKey("NominatedByBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("ResourceTutorNominations")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("ResourceTutorNominations")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionAiAssessment", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("AiAssessment")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.SessionAiAssessment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "GeneratedBy")
                        .WithMany()
                        .HasForeignKey("GeneratedByBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("GeneratedBy");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionExecution", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("SessionExecution")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.SessionExecution", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionMessage", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("SessionMessages")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionReview", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("SessionReviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SettingAuditLog", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "ChangedBy")
                        .WithMany("SettingAuditLogs")
                        .HasForeignKey("ChangedByBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.StudentEvaluation", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("StudentEvaluation")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.StudentEvaluation", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "BcUser")
                        .WithOne("Tutor")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.Tutor", "BcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", "Programme")
                        .WithMany("Tutors")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BcUser");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorApplicationReviewDecision", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Reviewer")
                        .WithMany("TutorApplicationReviewDecisions")
                        .HasForeignKey("ReviewerBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("ApplicationReviewDecisions")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorAvailabilities")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("TutorCourseModules")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorCourseModules")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorDeregistrationRequest", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("DeregistrationRequests")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorDocument", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorDocuments")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorModuleChangeRequest", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("TutorModuleChangeRequests")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("ModuleChangeRequests")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorStudentEvaluation", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("TutorEvaluation")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.TutorStudentEvaluation", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.UserNotification", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientBcUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BcUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Notifications");

                    b.Navigation("ResourceComments");

                    b.Navigation("SettingAuditLogs");

                    b.Navigation("Tutor");

                    b.Navigation("TutorApplicationReviewDecisions");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.Navigation("AdminSessionReview");

                    b.Navigation("AiAssessment");

                    b.Navigation("Documents");

                    b.Navigation("MeetingLink");

                    b.Navigation("PreparationLinks");

                    b.Navigation("SessionExecution");

                    b.Navigation("SessionMessages");

                    b.Navigation("SessionReviews");

                    b.Navigation("StatusHistory");

                    b.Navigation("StudentEvaluation");

                    b.Navigation("TutorEvaluation");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.CampusEvent", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResource", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeModule", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LearningResources");

                    b.Navigation("ResourceTutorNominations");

                    b.Navigation("TutorCourseModules");

                    b.Navigation("TutorModuleChangeRequests");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", b =>
                {
                    b.Navigation("ProgrammeModules");

                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.StudyArea", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.Navigation("ApplicationReviewDecisions");

                    b.Navigation("DeregistrationRequests");

                    b.Navigation("LearningResources");

                    b.Navigation("ModuleChangeRequests");

                    b.Navigation("ResourceTutorNominations");

                    b.Navigation("TutorAvailabilities");

                    b.Navigation("TutorCourseModules");

                    b.Navigation("TutorDocuments");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
