// <auto-generated />
using System;
using BC_CampusLearn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BC_CampusLearn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921070410_AddAdminSessionReview")]
    partial class AddAdminSessionReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("BcUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AdminId");

                    b.HasIndex("BcUserId")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.AdminSessionReview", b =>
                {
                    b.Property<int>("AdminSessionReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminSessionReviewId"));

                    b.Property<bool>("AllReviewsSubmitted")
                        .HasColumnType("bit");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<bool>("ConcernsResolvedOrDocumented")
                        .HasColumnType("bit");

                    b.Property<bool>("EvidenceSupportsApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadConfirmedQuality")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadConfirmedSession")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReviewerBcUserId")
                        .HasColumnType("int");

                    b.HasKey("AdminSessionReviewId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ReviewerBcUserId");

                    b.ToTable("AdminSessionReview", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BcUser", b =>
                {
                    b.Property<int>("BcUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BcUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsPublicActivityEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PublicActivityDisabledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicActivityDisabledReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("BcUserId");

                    b.HasIndex("PersonnelNumber")
                        .IsUnique();

                    b.ToTable("BcUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_BcUsers_Role", "[Role] BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateBooked")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ScheduledStartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StudentBcUserId")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("ProgrammeModuleId");

                    b.HasIndex("StudentBcUserId");

                    b.HasIndex("TutorId", "ProgrammeModuleId");

                    b.HasIndex("TutorId", "ScheduledStartTime");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Duration_OneHour", "[Duration] = 1");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingDocument", b =>
                {
                    b.Property<int>("BookingDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDocumentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BookingDocumentId");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.ToTable("BookingDocuments", t =>
                        {
                            t.HasCheckConstraint("CK_BookingDocuments_Position", "[Position] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingPreparationLink", b =>
                {
                    b.Property<int>("BookingPreparationLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingPreparationLinkId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("BookingPreparationLinkId");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.ToTable("BookingPreparationLinks", t =>
                        {
                            t.HasCheckConstraint("CK_BookingPreparationLinks_Position", "[Position] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingStatusHistory", b =>
                {
                    b.Property<int>("BookingStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingStatusHistoryId"));

                    b.Property<bool>("AvailabilityReopened")
                        .HasColumnType("bit");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ChangedByBcUserId")
                        .HasColumnType("int");

                    b.Property<bool>("ChangedBySystem")
                        .HasColumnType("bit");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("BookingStatusHistoryId");

                    b.HasIndex("ChangedByBcUserId");

                    b.HasIndex("BookingId", "ChangedAt");

                    b.ToTable("BookingStatusHistory", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResource", b =>
                {
                    b.Property<int>("LearningResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningResourceId"));

                    b.Property<bool>("AllowSubscriberComments")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset?>("DatePublished")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Link1")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Link2")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TutorLastViewedDiscussionAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LearningResourceId");

                    b.HasIndex("ProgrammeModuleId");

                    b.HasIndex("TutorId", "Status", "DateCreated");

                    b.ToTable("LearningResource", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResourceDocument", b =>
                {
                    b.Property<int>("ResourceDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceDocumentId"));

                    b.Property<DateTimeOffset>("DateUploaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("ResourceDocumentId");

                    b.HasIndex("ResourceId");

                    b.ToTable("LearningResourceDocuments", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.MeetingLink", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("BookingId");

                    b.ToTable("MeetingLink", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeModule", b =>
                {
                    b.Property<int>("ProgrammeModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgrammeModuleId"));

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("ProgrammeModuleId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("ProgrammeModule", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProgrammeOfStudy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bachelor of Computing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bachelor of Information Technology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diploma in Information Technology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diploma for Deaf Students"
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("ResourceId", "IsPinned", "DateCreated");

                    b.ToTable("ResourceComments", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceSubscription", b =>
                {
                    b.Property<int>("ResourceSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceSubscriptionId"));

                    b.Property<DateTimeOffset>("DateSubscribed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResourceSubscriptionId");

                    b.HasIndex("PersonnelNumber", "ModuleCode")
                        .IsUnique();

                    b.ToTable("ResourceSubscriptions", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionExecution", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpectedCompletionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StartSource")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BookingId");

                    b.HasIndex("ExpectedCompletionAt");

                    b.ToTable("SessionExecutions", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionMessage", b =>
                {
                    b.Property<long>("SessionMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionMessageId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("RecipientBcUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderBcUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SessionMessageId");

                    b.HasIndex("SenderBcUserId");

                    b.HasIndex("BookingId", "SentAt");

                    b.HasIndex("RecipientBcUserId", "ReadAt", "SentAt");

                    b.ToTable("SessionMessages", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionReview", b =>
                {
                    b.Property<int>("SessionReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionReviewId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int?>("RevieweeBcUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerBcUserId")
                        .HasColumnType("int");

                    b.HasKey("SessionReviewId");

                    b.HasIndex("RevieweeBcUserId");

                    b.HasIndex("ReviewerBcUserId");

                    b.HasIndex("BookingId", "ReviewerBcUserId")
                        .IsUnique();

                    b.ToTable("SessionReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionReviews_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.StudentEvaluation", b =>
                {
                    b.Property<int>("StudentEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentEvaluationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ImproveBCProgramme")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte>("ModeRating")
                        .HasColumnType("tinyint");

                    b.Property<string>("PlatformExperience")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("PlatformRating")
                        .HasColumnType("tinyint");

                    b.Property<string>("TutorAdvice")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TutorExplanation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TutorFriendliness")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TutorHelp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TutorInterest")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TutorParticipation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TutorPunctuality")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TutorResponse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TutorTopic")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TutoringMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TutoringService")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StudentEvaluationId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("StudentEvaluations", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudentEvaluations_ModeRating", "[ModeRating] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_StudentEvaluations_PlatformRating", "[PlatformRating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<int>("ApplicationStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("BcUserId")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CampusOfStudy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DemonstrationVideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InterviewDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("InterviewLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InterviewNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InterviewPreparationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("InterviewScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OverallAverage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("PreferredTutoringMode")
                        .HasColumnType("int");

                    b.Property<string>("PreviousTutoringExperience")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForTutoring")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortlistReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("TeachingStyle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("TutorId");

                    b.HasIndex("BcUserId")
                        .IsUnique();

                    b.HasIndex("ProgrammeId");

                    b.ToTable("Tutors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tutors_InterviewDurationMinutes", "[InterviewDurationMinutes] IS NULL OR [InterviewDurationMinutes] BETWEEN 15 AND 240");

                            t.HasCheckConstraint("CK_Tutors_OverallAverage", "[OverallAverage] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Tutors_YearOfStudy", "[YearOfStudy] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorApplicationReviewDecision", b =>
                {
                    b.Property<int>("TutorApplicationReviewDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorApplicationReviewDecisionId"));

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NewStage")
                        .HasColumnType("int");

                    b.Property<int>("PreviousStage")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerBcUserId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorApplicationReviewDecisionId");

                    b.HasIndex("ReviewerBcUserId");

                    b.HasIndex("TutorId", "ReviewedAt");

                    b.ToTable("TutorApplicationReviewDecisions", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorApplicationSettings", b =>
                {
                    b.Property<int>("TutorApplicationSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorApplicationSettingsId"));

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<bool>("ContinueAfterShortlistLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotifyStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("date");

                    b.Property<int?>("ShortlistLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("TutorApplicationSettingsId");

                    b.ToTable("TutorApplicationSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_TutorApplicationSettings_ShortlistLimit", "[ShortlistLimit] IS NULL OR [ShortlistLimit] > 0");

                            t.HasCheckConstraint("CK_TutorApplicationSettings_Singleton", "[TutorApplicationSettingsId] = 1");
                        });

                    b.HasData(
                        new
                        {
                            TutorApplicationSettingsId = 1,
                            ContinueAfterShortlistLimit = false,
                            IsOpen = false,
                            NotifyStudents = false,
                            UpdatedAt = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.Property<int>("TutorAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorAvailabilityId"));

                    b.Property<DateTimeOffset>("AvailableTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorAvailabilityId");

                    b.HasIndex("TutorId", "AvailableTime")
                        .IsUnique();

                    b.ToTable("TutorAvailabilities");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "ProgrammeModuleId");

                    b.HasIndex("ProgrammeModuleId");

                    b.ToTable("TutorCourseModules");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorDeregistrationRequest", b =>
                {
                    b.Property<int>("TutorDeregistrationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorDeregistrationRequestId"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorDeregistrationRequestId");

                    b.HasIndex("TutorId", "Status");

                    b.ToTable("TutorDeregistrationRequests");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorDocument", b =>
                {
                    b.Property<int>("TutorDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorDocumentId"));

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TutorDocumentId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorDocuments", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorModuleChangeRequest", b =>
                {
                    b.Property<int>("TutorModuleChangeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorModuleChangeRequestId"));

                    b.Property<int>("ProgrammeModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorModuleChangeRequestId");

                    b.HasIndex("ProgrammeModuleId");

                    b.HasIndex("TutorId", "ProgrammeModuleId", "Status");

                    b.ToTable("TutorModuleChangeRequests");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorStudentEvaluation", b =>
                {
                    b.Property<int>("TutorEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorEvaluationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousHomework")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RecordingLink")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("SessionPlan")
                        .HasColumnType("bit");

                    b.Property<string>("StudentFocus")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StudentInteract")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StudentIssues")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("StudentPreparationInfo")
                        .HasColumnType("bit");

                    b.Property<bool>("StudentPrepared")
                        .HasColumnType("bit");

                    b.Property<bool>("StudentPunctuality")
                        .HasColumnType("bit");

                    b.Property<string>("TutorComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TutorEvaluationId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("TutorStudentEvaluations", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.UserNotification", b =>
                {
                    b.Property<long>("UserNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserNotificationId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1400)
                        .HasColumnType("nvarchar(1400)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecipientBcUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("UserNotificationId");

                    b.HasIndex("RecipientBcUserId", "ReadAt", "CreatedAt");

                    b.ToTable("UserNotifications", (string)null);
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Admin", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "BcUser")
                        .WithOne("Admin")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.Admin", "BcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BcUser");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.AdminSessionReview", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("AdminSessionReview")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.AdminSessionReview", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("Bookings")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "StudentBcUser")
                        .WithMany()
                        .HasForeignKey("StudentBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BC_CampusLearn.Models.Entities.TutorCourseModule", "TutorCourseModule")
                        .WithMany("Bookings")
                        .HasForeignKey("TutorId", "ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("StudentBcUser");

                    b.Navigation("TutorCourseModule");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingDocument", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("Documents")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingPreparationLink", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("PreparationLinks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "ChangedByBcUser")
                        .WithMany()
                        .HasForeignKey("ChangedByBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("ChangedByBcUser");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResource", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("LearningResources")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("LearningResources")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResourceDocument", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.LearningResource", "Resource")
                        .WithMany("Documents")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.MeetingLink", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("MeetingLink")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.MeetingLink", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeModule", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", "Programme")
                        .WithMany("ProgrammeModules")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceComment", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Author")
                        .WithMany("ResourceComments")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ResourceComments_Authors");

                    b.HasOne("BC_CampusLearn.Models.Entities.ResourceComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ResourceComments_Parent");

                    b.HasOne("BC_CampusLearn.Models.Entities.LearningResource", "Resource")
                        .WithMany("Comments")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ResourceComments_Resources");

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionExecution", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("SessionExecution")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.SessionExecution", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionMessage", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("SessionMessages")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.SessionReview", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithMany("SessionReviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeBcUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.StudentEvaluation", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("StudentEvaluation")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.StudentEvaluation", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "BcUser")
                        .WithOne("Tutor")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.Tutor", "BcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", "Programme")
                        .WithMany("Tutors")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BcUser");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorApplicationReviewDecision", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Reviewer")
                        .WithMany("TutorApplicationReviewDecisions")
                        .HasForeignKey("ReviewerBcUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("ApplicationReviewDecisions")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorAvailability", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorAvailabilities")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("TutorCourseModules")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorCourseModules")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorDeregistrationRequest", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("DeregistrationRequests")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorDocument", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorDocuments")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorModuleChangeRequest", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.ProgrammeModule", "ProgrammeModule")
                        .WithMany("TutorModuleChangeRequests")
                        .HasForeignKey("ProgrammeModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC_CampusLearn.Models.Entities.Tutor", "Tutor")
                        .WithMany("ModuleChangeRequests")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeModule");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorStudentEvaluation", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.Booking", "Booking")
                        .WithOne("TutorEvaluation")
                        .HasForeignKey("BC_CampusLearn.Models.Entities.TutorStudentEvaluation", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.UserNotification", b =>
                {
                    b.HasOne("BC_CampusLearn.Models.Entities.BcUser", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientBcUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.BcUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Notifications");

                    b.Navigation("ResourceComments");

                    b.Navigation("Tutor");

                    b.Navigation("TutorApplicationReviewDecisions");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Booking", b =>
                {
                    b.Navigation("AdminSessionReview");

                    b.Navigation("Documents");

                    b.Navigation("MeetingLink");

                    b.Navigation("PreparationLinks");

                    b.Navigation("SessionExecution");

                    b.Navigation("SessionMessages");

                    b.Navigation("SessionReviews");

                    b.Navigation("StatusHistory");

                    b.Navigation("StudentEvaluation");

                    b.Navigation("TutorEvaluation");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.LearningResource", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeModule", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LearningResources");

                    b.Navigation("TutorCourseModules");

                    b.Navigation("TutorModuleChangeRequests");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ProgrammeOfStudy", b =>
                {
                    b.Navigation("ProgrammeModules");

                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.ResourceComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.Tutor", b =>
                {
                    b.Navigation("ApplicationReviewDecisions");

                    b.Navigation("DeregistrationRequests");

                    b.Navigation("LearningResources");

                    b.Navigation("ModuleChangeRequests");

                    b.Navigation("TutorAvailabilities");

                    b.Navigation("TutorCourseModules");

                    b.Navigation("TutorDocuments");
                });

            modelBuilder.Entity("BC_CampusLearn.Models.Entities.TutorCourseModule", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
